### ISSUE TITLE
As a member of a lobby, I want to be redirected to the event page after the event has been successfully created in order to have an overview of the event.

### ISSUE THREAD

**Issue by patrick9051** [sopra-fs23-group-07/sopra-fs23-group-07-server#10]
**Acceptance Criteria:**
- [x] Information on the sport, time, location, etc. shown as a table. 
- [x] The agreed-upon location will be shown as a map (with the Mapbox API). 
- [x] A list of the other members that will participate in the event is shown. (optional)
- [x] Upon clicking the user, the user is redirected to the respective profile page. 
 
**Development Tasks BE:**
- [x] sopra-fs23-group-07/sopra-fs23-group-07-server#74
- [x] sopra-fs23-group-07/sopra-fs23-group-07-server#75
- [x] sopra-fs23-group-07/sopra-fs23-group-07-server#76
- [x] sopra-fs23-group-07/sopra-fs23-group-07-server#77
- [x] sopra-fs23-group-07/sopra-fs23-group-07-server#78
- [x] sopra-fs23-group-07/sopra-fs23-group-07-server#79

**Development Tasks FE:**
- [x] sopra-fs23-group-07/sopra-fs23-group-07-client#4
- [x] sopra-fs23-group-07/sopra-fs23-group-07-client#5
- [x] sopra-fs23-group-07/sopra-fs23-group-07-client#6
