### ISSUE TITLE
As a non-registered user, I want to see a map and a table showing all current sport events so that I may find one which is suitable for me to join.

### ISSUE THREAD

**Issue by patrick9051** [sopra-fs23-group-07/sopra-fs23-group-07-server#11]
**Acceptance Criteria:**
- [x] The current sports events, which have been agreed upon in a lobby, are shown in a list as well as on a map. 
- [x] A map with all the current sports events is loaded when the user opens the home page. 
- [x] The list with all current sports events is shown on the left side of the screen. 
- [x] The sports events which are full will not be shown.  
- [x] Zooming in or out of the map allows the user to get a more detailed or broader view of the map. 

**Development Tasks BE:**
- [x] sopra-fs23-group-07/sopra-fs23-group-07-server#69

**Development Tasks FE:**
- [x] sopra-fs23-group-07/sopra-fs23-group-07-client#27
- [x] sopra-fs23-group-07/sopra-fs23-group-07-client#28
- [x] sopra-fs23-group-07/sopra-fs23-group-07-client#29
