### ISSUE TITLE
As a non-registered user, I want to be able to filter the table and map of sports events in order to find an event that best suits my preferences.

### ISSUE THREAD

**Issue by patrick9051** [sopra-fs23-group-07/sopra-fs23-group-07-server#12]
**Acceptance Criteria:**
- [x] A user can filter the table and map with regards to the sport (e.g. football, basketball etc.). 
- [x] The filter is integrated in the table and the user can select filter and sorting criteria for each column
- [x] By specifying a start and end date/time, a user can filter by date and time. 
- [x] Upon clicking a dropdown menu, a user may choose one or multiple regions to filter by. 

**Development Tasks BE:**
- [x] sopra-fs23-group-07/sopra-fs23-group-07-server#64

**Development Tasks FE:**
- [x] sopra-fs23-group-07/sopra-fs23-group-07-client#32
- [x] sopra-fs23-group-07/sopra-fs23-group-07-client#31
- [x] sopra-fs23-group-07/sopra-fs23-group-07-client#134
- [x] sopra-fs23-group-07/sopra-fs23-group-07-client#149
