### ISSUE TITLE
Optional - As a logged-in user, I want to see all the events that I have signed up for so that I may plan my day accordingly.

### ISSUE THREAD

**Issue by patrick9051** [sopra-fs23-group-07/sopra-fs23-group-07-server#13]
**Acceptance Criteria:**
- [ ] Upon clicking on My Events in the navigational bar, the user will be redirected to a page containing information on all events the user has signed up for.
- [ ] Each event will contain information on the sport, time, location and participants. 
- [ ] Upon clicking on a user, the user will be redirected to the user's profile page. 
- [ ] On the My Events page some key statistics about the user’s events are displayed.

**Development Tasks BE:**
- [x] sopra-fs23-group-07/sopra-fs23-group-07-server#58
- [ ] sopra-fs23-group-07/sopra-fs23-group-07-server#59

**Development Tasks FE:**
- [x] sopra-fs23-group-07/sopra-fs23-group-07-client#33
- [ ] sopra-fs23-group-07/sopra-fs23-group-07-client#34
- [x] sopra-fs23-group-07/sopra-fs23-group-07-client#35
- [ ] sopra-fs23-group-07/sopra-fs23-group-07-client#36
