### ISSUE TITLE
Optional - As a logged-in user, I want to directly create an event and decide on all the details (sport, location, time, etc.) so that I can have an event that exactly meets my preferences.

### ISSUE THREAD

**Issue by patrick9051** [sopra-fs23-group-07/sopra-fs23-group-07-server#14]
**Acceptance Criteria:**
- [ ] Lobby creation remains the same as when creating a normal lobby with other users. 
- [ ] Upon clicking the create direct event button, the user is redirected to a create direct event page where the user can select all the options they want. 
- [ ] Selecting options (sport, time, location, etc.) for the event remains the same as in the normal lobby. 

**Development Tasks BE:**
- [x] sopra-fs23-group-07/sopra-fs23-group-07-server#53

**Development Tasks FE:**
- [ ] sopra-fs23-group-07/sopra-fs23-group-07-client#40
- [ ] sopra-fs23-group-07/sopra-fs23-group-07-client#39
- [ ] sopra-fs23-group-07/sopra-fs23-group-07-client#38
- [ ] sopra-fs23-group-07/sopra-fs23-group-07-client#37
