### ISSUE TITLE
As a logged-in user, I want to be able to join a lobby from the current open lobbies page.

### ISSUE THREAD

**Issue by theraffael** [sopra-fs23-group-07/sopra-fs23-group-07-server#17]
**Acceptance Criteria:**

- [x] User can see and click on a join button on the overview view page.
- [x] After clicking the join button, the user gets redirected to the respective lobby.
- [x] After clicking the join button, the user becomes a member of the respective lobby.

**Development Tasks BE:**
- [x] sopra-fs23-group-07/sopra-fs23-group-07-server#41
- [x] sopra-fs23-group-07/sopra-fs23-group-07-server#42
- [x] sopra-fs23-group-07/sopra-fs23-group-07-server#43
- [x] sopra-fs23-group-07/sopra-fs23-group-07-server#44
- [x] sopra-fs23-group-07/sopra-fs23-group-07-server#45

**Development Tasks FE:**
- [x] sopra-fs23-group-07/sopra-fs23-group-07-client#45
- [x] sopra-fs23-group-07/sopra-fs23-group-07-client#46
