### ISSUE TITLE
As a member of a lobby, I want to be able to put a marker  on the map to show it as my preference for the sports event.

### ISSUE THREAD

**Issue by theraffael** [sopra-fs23-group-07/sopra-fs23-group-07-server#19]
**Acceptance Criteria:**
- [x] User can see a map in the lobby and click on any field in the map. 
- [x] After clicking on any field in the map a marker will be set. 
- [x] After a marker was set an address will be shown under the map that allows users to click on it as a vote for this preference. 

**Development Tasks BE:**

**Development Tasks FE:**
- [x] sopra-fs23-group-07/sopra-fs23-group-07-client#51
- [x] sopra-fs23-group-07/sopra-fs23-group-07-client#50
- [x] sopra-fs23-group-07/sopra-fs23-group-07-client#49
