### ISSUE TITLE
As a logged-in user, I want to edit my own user profile to update my username, password, email address, birthday and bio.

### ISSUE THREAD

**Issue by patrick9051** [sopra-fs23-group-07/sopra-fs23-group-07-server#2]
**Acceptance criteria:**
- [x] Upon clicking on the edit profile button on the user's profile page, the user is able to change his/her username, password. email address, birthday and bio. 
- [x] A registered user can only change their own profile and not the profiles of other users.
- [x] After changing and saving the data, the user is redirected to the profile page and the new/changed data is displayed. 
- [x] The given username and/or email address must be unique. 
- [x] The username, password and/or email address are non-empty words. 

**Development Tasks BE:**
- [x] sopra-fs23-group-07/sopra-fs23-group-07-server#118
- [x] sopra-fs23-group-07/sopra-fs23-group-07-server#119
- [x] sopra-fs23-group-07/sopra-fs23-group-07-server#120

**Development Tasks FE:**
- [x] sopra-fs23-group-07/sopra-fs23-group-07-client#25
- [x] sopra-fs23-group-07/sopra-fs23-group-07-client#26
- [x] sopra-fs23-group-07/sopra-fs23-group-07-client#58
- [x] sopra-fs23-group-07/sopra-fs23-group-07-client#59
