### ISSUE TITLE
As a logged-in user, I want to create an lobby, so other users can see and join this lobby. I create a lobby in order to schedule real life sports events with friends and/or strangers in which we agree together on a sport, location and time.

### ISSUE THREAD

**Issue by patrick9051** [sopra-fs23-group-07/sopra-fs23-group-07-server#3]
**Acceptance Criteria:**
- [ ] Upon clicking the create lobby button, the user is redirected to the choose-region page, which is the first step in creating a lobby. 
- [ ] When creating the lobby, the user must choose a region (canton within Switzerland) from a dropdown menu, where the event is taking place. 
- [ ] The user chooses a lobby name, which is a non-empty string. 
- [ ] Upon clicking the confirm button, the event lobby is created.  
- [ ] Upon clicking the share button, the user is shown a link to the event lobby (clipboard option), which can be used by friends to join the event lobby. 

**Development Tasks BE:**
- [x] sopra-fs23-group-07/sopra-fs23-group-07-server#106
- [x] sopra-fs23-group-07/sopra-fs23-group-07-server#107
- [x] sopra-fs23-group-07/sopra-fs23-group-07-server#108
- [x] sopra-fs23-group-07/sopra-fs23-group-07-server#109
- [ ] sopra-fs23-group-07/sopra-fs23-group-07-server#110
- [ ] sopra-fs23-group-07/sopra-fs23-group-07-server#111
- [x] sopra-fs23-group-07/sopra-fs23-group-07-server#112
- [ ] sopra-fs23-group-07/sopra-fs23-group-07-server#113

**Development Tasks FE:**
- [x] sopra-fs23-group-07/sopra-fs23-group-07-client#21
- [x] sopra-fs23-group-07/sopra-fs23-group-07-client#22
- [x] sopra-fs23-group-07/sopra-fs23-group-07-client#23
- [x] sopra-fs23-group-07/sopra-fs23-group-07-client#24
