### ISSUE TITLE
As a logged-in user, I want to see an overview (lobby name, region, number of members in a lobby & time left) of all open lobbies on the lobbies screen in order to join a lobby.

### ISSUE THREAD

**Issue by patrick9051** [sopra-fs23-group-07/sopra-fs23-group-07-server#4]
**Acceptance Criteria:**
- [x] All open lobbies are displayed as a table, where each columns contains information on the lobby name, region, number of members in the lobby and the time left. 
- [x] By clicking on the lobby the user gets redirected to the respective lobby’s page. 
- [x] Upon clicking a join lobby button the user is redirected to the respective lobby page. 
- [x] Once the voting process of a lobby has started, it will not be shown in the list anymore.  

**Development Tasks BE:**
- [x] sopra-fs23-group-07/sopra-fs23-group-07-server#101
- [x] sopra-fs23-group-07/sopra-fs23-group-07-server#102

**Development Tasks FE:**
- [x] sopra-fs23-group-07/sopra-fs23-group-07-client#18
- [x] sopra-fs23-group-07/sopra-fs23-group-07-client#19
- [x] sopra-fs23-group-07/sopra-fs23-group-07-client#20
