### ISSUE TITLE
As a member of a lobby, I want to be able to select my preference for each category (sport, location, time, etc.) in order to agree on an event with the other members.

### ISSUE THREAD

**Issue by patrick9051** [sopra-fs23-group-07/sopra-fs23-group-07-server#6]
**Acceptance Criteria:**
- [x] Upon clicking a dropdown menu for any of the categories (sport, time, location, the maximum number of participants), a list containing multiple options for the respective category is shown, where an option from the list can be chosen. 
- [x] Multiple options for each category can be chosen. 
- [x] All chosen options are shown on the screen as tags. 
- [x] A member of the lobby can put in for the next 7 days at which time they are free for the sports event. 
- [x] A member of the lobby can put in which locations they would like the event to be held.  
- [x] The host of the lobby can put in the maximum number of participants they want to allow for the event. 

**Development Tasks BE:**
- [x] sopra-fs23-group-07/sopra-fs23-group-07-server#92
- [x] sopra-fs23-group-07/sopra-fs23-group-07-server#93

**Development Tasks FE:**
- [x] sopra-fs23-group-07/sopra-fs23-group-07-client#11
- [x] sopra-fs23-group-07/sopra-fs23-group-07-client#12
- [x] sopra-fs23-group-07/sopra-fs23-group-07-client#13
- [x] sopra-fs23-group-07/sopra-fs23-group-07-client#14
- [x] sopra-fs23-group-07/sopra-fs23-group-07-client#15
